title: Fields
modelClass: Dibrovnik\Partnerprofile\Models\Field
list: $/dibrovnik/partnerprofile/models/field/columns.yaml
recordUrl: 'dibrovnik/partnerprofile/Fields/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
