list: $/dibrovnik/partnerprofile/models/taxonomy/columns.yaml
modelClass: Dibrovnik\Partnerprofile\Models\Taxonomy
title: Taxonomy
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dibrovnik/partnerprofile/taxonomy/update/:id'
