list: $/dibrovnik/partnerprofile/models/category/columns.yaml
modelClass: Dibrovnik\Partnerprofile\Models\Category
title: Category
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dibrovnik/partnerprofile/category/update/:id'
