list: $/dibrovnik/partnerprofile/models/partner/columns.yaml
modelClass: Dibrovnik\Partnerprofile\Models\Partner
title: PartnersController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dibrovnik/partnerprofile/partnerscontroller/update/:id'
