list: $/dibrovnik/partnerprofile/models/price/columns.yaml
modelClass: Dibrovnik\Partnerprofile\Models\Price
title: Prices
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dibrovnik/partnerprofile/prices/update/:id'
